language: python

sudo: false

python:
  - '3.4'
  - '3.5'
  - '3.6'

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes -q conda
  - conda config --set always_yes true
  - conda config --set anaconda_upload no
  - conda config --add channels conda-forge

install:
  - conda install -q python=$TRAVIS_PYTHON_VERSION pip conda-build anaconda-client
  - conda build recipe/
  - conda install --use-local statusbar

after_success:
  - chmod +x ./deploy_conda.sh

deploy:
  - provider: script
    script: ./deploy_conda.sh
    skip_cleanup: true
    skip_upload_docs: true
    on:
      tags: true
      python: 3.4
